scrape_configs:
  - job_name: "gcdemoapp"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 10s
    static_configs:
      - targets: ["192.168.68.111:8080"]
        labels:
          application: "gcdemoapp"
